### ISSUE TITLE
Include science in UMD build

### ISSUE THREAD

**Issue by curran** [jdfekete/reorder.js#12]
Currently, as pointed out by @Fil, the UMD build currently does _not_ include science.js, but should.

This is probably a matter of getting the right Rollup configuration, relating to "externals".

**Comment by curran** [comment]
It appears that the entire `science` library _is_ included in the UMD bundle.

**Comment by Fil** [comment]
It's included with "use strict;", and since science.js calls the (global) `science` symbol without defining it, it breaks.

**Comment by curran** [comment]
Interesting.. Yes and I see it's wrapped twice in a function of sorts.

```
        (function(exports){
        (function(exports){    
        science = {version: "1.9.1"}; // semver 
        science.ascending = function(a, b) {
          return a - b;        
        };                     
        // Euler's constant.   
        science.EULER = .5772156649015329;
```

**Comment by curran** [comment]
Possibly related https://github.com/jasondavies/science.js/issues/27

**Comment by curran** [comment]
I wonder if there's any active fork that does a proper distribution...

**Comment by curran** [comment]
This is a PR on `science.js` that does a proper build.

https://github.com/jasondavies/science.js/pull/26

**Comment by curran** [comment]
https://github.com/jasondavies/science.js/issues/33

**Comment by curran** [comment]
It appears the best solution may in fact be to just use the `@sgratzl/science` package.
