### ISSUE TITLE
Add minified versions of the library

### ISSUE THREAD

**Issue by jdfekete** [jdfekete/reorder.js#18]

**Comment by curran** [comment]
Best options include the following two Rollup plugins:
 * https://github.com/TrySound/rollup-plugin-uglify
 * https://github.com/TrySound/rollup-plugin-terser

At first glance, I think either choice would work just fine.

**Comment by jdfekete** [comment]
Used terser since uglify plugin README says: "Note: uglify-js is able to transpile only es5 syntax. If you want to transpile es6+ syntax use terser instead".
Only minified the umd version, not cjs and es. Maybe one of them should, or a minified version should be added?
Not sure if it is important.

**Comment by curran** [comment]
It might be good to also minify the es build, as module loaders may pull that in directly from a CDN, like the UMD build. For cjs I don't think it matters.
