### ISSUE TITLE
Fix d3.parcoords reordering function

### ISSUE THREAD

**Issue by jdfekete** [jdfekete/reorder.js#23]
The current implementation works on https://github.com/syntagmatic/parallel-coordinates, which is outdated. Fortunately, a new implementation is available at https://github.com/BigFatDog/parcoords-es; it seems modern enough.
The current function `reorder.parcoords` needs to be improved to handle all the data types handled by the library, and to do the right operations, ignoring the hidden attributes and the non-numeric ones as well.

**Comment by curran** [comment]
Oh wow this would be a fun project!

**Comment by jdfekete** [comment]
Fixed parcoords in pcp.js to work with d3.parcoords, the old version. Updated (simplified) examples/cars/index.html to use it.
Still need to test with the new version of parcoords-es. The function parcoords-es() is in pcp.js but it is not tested yet.

**Comment by jdfekete** [comment]
reorder.parcoords_es now works with the parcoord-es package.
