### ISSUE TITLE
Mention Bertifier in README

### ISSUE THREAD

**Issue by curran** [jdfekete/reorder.js#26]
It may be nice to include a link to [Bertifier](https://aviz.fr/bertifier) in the README here.

Interestingly, I cannot seem to locate the Open Source code for Bertifier. It's mentioned in the paper that it is Open Source, but I'm not sure where to look for it.

**Comment by jdfekete** [comment]
Good that you asked. It's been kept in an old Inria gforge repo. I am moving it to a gitlab repo. I think the code is very dirty but it may be inspirational if someone wants to rewrite it. https://gitlab.inria.fr/aviz/bertifier/

**Comment by curran** [comment]
Nice! GitHub would be amazing, as it it sort of the gold standard, as compared to GitLab which is not as widely used.

**Comment by curran** [comment]
I'm not able to follow that link. This is what I see:

![image](https://user-images.githubusercontent.com/68416/103463030-43058380-4cf7-11eb-8303-bc866a2ca55d.png)

**Comment by jdfekete** [comment]
Ok, it is moved to https://github.com/jdfekete/bertifier now
