### ISSUE TITLE
Refresh the code - finishing touches

### ISSUE THREAD

**Issue by curran** [jdfekete/reorder.js#27]
As a follow-on to #19, as implemented in https://github.com/jdfekete/reorder.js/pull/25, there are a few more finishing touches I'd like to do after that PR gets merged:

 * Run Lebab over it _again_, with all transforms, which may be able to clean up some of the `for` loops to `for ... of` loops, now that the `let i` definitions have been inlined.
 * Add braces for all `for` and `if` statements.

That second idea may be controversial as it's a matter of coding style. To provide some justification, as I was going through the code, I constantly found it confusing to encounter lines like this:

```js
  if (!directed) directed = graph.directed();
```

I personally find that structure difficult to parse visually when reading through the code. It takes more effort to understand the above variant than it does to understand the following variant of it:

```js
  if (!directed) {
    directed = graph.directed();
  }
```

Moreover, this pattern is currently inconsistent across the codebase. Sometimes the braces are there, and sometimes they are not. For consistency alone, I believe the argument to introduce these braces everywhere is strong.

I researched this a bit and it appears [possible to add these curly braces automatically](https://stackoverflow.com/questions/54065344/how-to-get-prettier-to-add-braces-when-mssing-on-if-else) using ESLint with the `--fix` option. I would recommend we do this as a final clean-up phase. However, it is a personal stylistic preference, so if the decision to leave out the braces was quite intentional, I respect that and we can skip this step.

**Comment by jdfekete** [comment]
I have added the braces with eslint, see the .eslintrc configuration.
