### ISSUE TITLE
sorting array of objects?

### ISSUE THREAD

**Issue by mgiraldo** [jdfekete/reorder.js#5]
I have an array of the form that I would like to sort by its `h`, `l`, `s` values (colors) while keeping the index in place:

```
[
  { h: 1.0, s: 1.0, l: 0.0, i: 1 },
  { h: 0.2, s: 0.0, l: 0.1, i: 2 },
  { h: 0.6, s: 0.3, l: 0.2, i: 3 },
  ...
]
```

The cars example uses `pcp` and `array_to_dicts` but these are not documented in the Wiki and not present in the `reorder.d.ts` file. I tried importing it via `import reorder from 'reorder.js'` and doing:

```
  const pcp = reorder.pcp(myArray, ['h', 's', 'l'])
```

and get `Property 'pcp' does not exist on type 'typeof reorder'.` I tried adding `pcp`to the type definition file but got additional errors (`science is not defined`).

I know the example does not use `import` but I was wondering if it was possible to use it this way.

**Comment by MoritzStefaner** [comment]
I had trouble as well to get an import to work. I ended up including the scripts in the html head
```
	<script src="./reorder/lib/science.v1.js"></script>
	<script src="./reorder/lib/tiny-queue.js"></script>
	<script src="./reorder/reorder.v1.js"></script>
```

**Comment by jdfekete** [comment]
My code is very old-fashioned. I have a TODO item to rewrite it using modern technologies but I cannot find the time to do it. If you use the old-fashioned <script ...> syntax that Moritz uses, it will work.
I will try to find a student to re-package this code correctly. Sorry for not being able to maintain it as well as I should.

**Comment by mgiraldo** [comment]
i understand @jdfekete 😀 open source is hard to maintain! thanks for the library!
