### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by curran** [jdfekete/reorder.js#9]
User Story: As a developer who is new to this project and looking to work on [modernizing the distribution](https://github.com/jdfekete/reorder.js/issues/8), I want to have a stable test harness to check what things break and how they break along the way towards modernization.

**Comment by curran** [comment]
To run the tests, I ran `make install` and `make test`.

The first broken test is this one:

```
    order 
      ✗ insert-simple 
      Invalid list, indices not sorted 
```

That test is defined here in the code, if anyone has capacity to investigate: https://github.com/jdfekete/reorder.js/blob/master/test/order-test.js#L151

**Comment by jdfekete** [comment]
Sure, let me check what's wrong. I have forgotten everything about that code so I need to find out what it is supposed to do.

**Comment by curran** [comment]
Hooray! Thank you for jumping in.

**Comment by jdfekete** [comment]
Fixed.
